name: Build and Upload Module

on:
  push:
    branches:
      - dev
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set artifact name
      id: artifact
      run: |
        short_sha=${GITHUB_SHA:0:7}
        echo "zip_name=liteDNS-${GITHUB_REF_NAME}-${short_sha}" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact.outputs.zip_name }}
        path: liteDNS